import { Palette } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const scanStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
    width: '100%',
  },
  webCameraContainer: {
    flex: 1,
    width: '100%',
    position: 'relative',
  },
  webOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  darkOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topDarkArea: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '15%',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  bottomDarkArea: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '15%',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  middleSection: {
    position: 'absolute',
    top: '15%',
    left: 0,
    right: 0,
    height: '70%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sideDarkArea: {
    flex: 1,
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.2)',
    pointerEvents: 'none',
  },
  scanFrame: {
    width: '80%',
    height: '70%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.5)',
    borderRadius: 12,
  },
  scanOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 40,
    pointerEvents: 'box-none',
  },
  scanAreaLoader: {
    marginBottom: 0,
  },
  instruction: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
  },
  loadingText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    marginBottom: 16,
    textAlign: 'center',
  },
  footerButton: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerPrimaryButton: {
    backgroundColor: Palette.primary,
  },
  footerButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  message: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  button: {
    backgroundColor: Palette.primary,
    padding: 16,
    borderRadius: 8,
  },
  buttonText: {
    color: Palette.white,
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    position: 'absolute',
    bottom: 40,
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  cancelText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalScrollView: {
    flex: 1,
    maxHeight: '90%',
  },
  modalContentContainer: {
    flexGrow: 1,
    justifyContent: 'flex-start',
  },
  modalContent: {
    backgroundColor: Palette.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: Palette.lightGray,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 12,
  },
  modalHeader: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: Palette.primary,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Palette.lightGray,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  closeButtonText: {
    fontSize: 18,
    color: Palette.darkGray,
    fontWeight: '600',
  },
  headerContent: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: Palette.primary,
    marginBottom: 6,
  },
  productName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: Palette.brown,
  },
  bestBeforeText: {
    fontSize: 13,
    color: '#d97706',
    fontWeight: '500',
    marginTop: 4,
  },
  // Image styles
  imageContainer: {
    width: 120,
    height: 120,
    alignSelf: 'center',
    marginBottom: 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
    borderWidth: 2,
    borderColor: '#ddd',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  tapToEnlarge: {
    position: 'absolute',
    bottom: 4,
    alignSelf: 'center',
    fontSize: 10,
    color: '#fff',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  enlargedImageOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  enlargedImageContainer: {
    width: '90%',
    height: '80%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  enlargedImage: {
    width: '100%',
    height: '100%',
  },
  closeText: {
    color: '#fff',
    fontSize: 14,
    marginTop: 16,
    opacity: 0.7,
  },
  // Best before box
  bestBeforeBox: {
    backgroundColor: '#fff9e6',
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#ffc107',
  },
  bestBeforeLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ff9800',
    marginBottom: 4,
  },
  bestBeforeValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#d97706',
  },
  // Nutrition box
  nutritionBox: {
    backgroundColor: Palette.primary,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 0,
  },
  nutritionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
    marginBottom: 12,
  },
  nutritionCalories: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Palette.white,
    marginBottom: 16,
  },
  macrosGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  macroItem: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.15)',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 0,
  },
  macroLabel: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
    marginBottom: 4,
  },
  macroValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Palette.white,
  },
  // Option buttons
  optionButton: {
    backgroundColor: Palette.primary,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: Palette.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  optionButtonText: {
    color: Palette.white,
    fontSize: 17,
    fontWeight: '600',
  },
  // Quantity container
  quantityContainer: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: Palette.lightGray2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  quantityLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: Palette.darkGray,
  },
  quantityInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  quantityButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    color: Palette.white,
    fontSize: 24,
    fontWeight: 'bold',
  },
  quantityInput: {
    flex: 1,
    backgroundColor: Palette.white,
    padding: 12,
    borderRadius: 8,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
    borderWidth: 2,
    borderColor: Palette.primary,
  },
  // Serving size
  servingSizeContainer: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: Palette.lightGray2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  servingSizeLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: Palette.darkGray,
  },
  servingSizeInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  servingSizeInput: {
    flex: 1,
    backgroundColor: Palette.white,
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '600',
    borderWidth: 1,
    borderColor: Palette.primary,
  },
  servingSizeUnit: {
    fontSize: 16,
    fontWeight: '600',
    color: Palette.darkGray,
  },
  servingSizeHint: {
    fontSize: 12,
    color: Palette.gray,
    marginTop: 8,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  servingSizeLabelRow: {
    marginBottom: 12,
  },
  // Meal container
  mealContainer: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: Palette.lightGray2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  mealChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  mealChip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: Palette.white,
    borderWidth: 1,
    borderColor: '#d5d5d5',
  },
  mealChipActive: {
    backgroundColor: Palette.primary,
    borderColor: Palette.primary,
  },
  mealChipText: {
    color: Palette.darkGray,
    fontWeight: '600',
    fontSize: 14,
  },
  mealChipTextActive: {
    color: Palette.white,
  },
  // Custom amount
  customAmountContainer: {
    marginBottom: 12,
    padding: 16,
    backgroundColor: Palette.lightGray,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Palette.orange,
  },
  customLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: Palette.brown,
  },
  customInputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  customInput: {
    flex: 1,
    backgroundColor: Palette.white,
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: Palette.primary,
  },
  customButton: {
    backgroundColor: Palette.primary,
    paddingHorizontal: 24,
    borderRadius: 8,
    justifyContent: 'center',
  },
  customButtonText: {
    color: Palette.white,
    fontSize: 16,
    fontWeight: '600',
  },
  cancelOptionButton: {
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#ddd',
    backgroundColor: '#f9f9f9',
  },
  cancelOptionText: {
    color: Palette.darkGray,
    fontSize: 16,
    fontWeight: '600',
  },
  // Unit selector
  unitSelector: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  unitButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderWidth: 1.5,
    borderColor: Palette.primary,
  },
  unitButtonActive: {
    backgroundColor: Palette.primary,
  },
  unitButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: Palette.primary,
  },
  unitButtonTextActive: {
    color: Palette.white,
  },
});
