import { Palette } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const scanStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
    width: '100%',
  },
  webCameraContainer: {
    flex: 1,
    width: '100%',
    position: 'relative',
  },
  webOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  darkOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topDarkArea: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '15%',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  bottomDarkArea: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '15%',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  middleSection: {
    position: 'absolute',
    top: '15%',
    left: 0,
    right: 0,
    height: '70%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sideDarkArea: {
    flex: 1,
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.8)',
    pointerEvents: 'none',
  },
  scanFrame: {
    width: '80%',
    height: '70%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  scanOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 40,
    pointerEvents: 'box-none',
  },
  scanAreaLoader: {
    marginBottom: 0,
  },
  instruction: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
  },
  loadingText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    marginBottom: 16,
    textAlign: 'center',
  },
  footerButton: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerPrimaryButton: {
    backgroundColor: Palette.primary,
  },
  footerButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  message: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  button: {
    backgroundColor: Palette.primary,
    padding: 16,
    borderRadius: 8,
  },
  buttonText: {
    color: Palette.white,
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    position: 'absolute',
    bottom: 40,
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  cancelText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalScrollView: {
    flex: 1,
    maxHeight: '90%',
  },
  modalContentContainer: {
    flexGrow: 1,
    justifyContent: 'flex-start',
  },
  modalContent: {
    backgroundColor: Palette.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: Palette.lightGray,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 12,
  },
  modalHeader: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: Palette.primary,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Palette.lightGray,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  closeButtonText: {
    fontSize: 18,
    color: Palette.darkGray,
    fontWeight: '600',
  },
  headerContent: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: Palette.primary,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  productName: {
    fontSize: 28,
    fontWeight: '800',
    color: Palette.brown,
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  // Image styles - Enhanced with better feedback
  imageContainer: {
    width: 140,
    height: 140,
    alignSelf: 'center',
    marginBottom: 20,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  imageSkeleton: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#e0e0e0',
    borderRadius: 16,
  },
  imagePinIcon: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePinText: {
    fontSize: 16,
  },
  tapToEnlarge: {
    position: 'absolute',
    bottom: 6,
    alignSelf: 'center',
    fontSize: 11,
    color: '#fff',
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    fontWeight: '600',
  },
  enlargedImageOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  enlargedImageContainer: {
    width: '90%',
    height: '80%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  enlargedImage: {
    width: '100%',
    height: '100%',
  },
  closeText: {
    color: '#fff',
    fontSize: 14,
    marginTop: 16,
    opacity: 0.7,
  },
  // Nutrition box - Bento style with gradients
  nutritionBox: {
    backgroundColor: 'transparent',
    padding: 0,
    marginBottom: 24,
  },
  nutritionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: Palette.gray,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  nutritionCalories: {
    fontSize: 48,
    fontWeight: '800',
    color: Palette.primary,
    marginBottom: 16,
    letterSpacing: -1,
  },
  macrosGrid: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  macroItem: {
    flex: 1,
    minWidth: '48%',
    backgroundColor: '#f8f8f8',
    padding: 14,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e8e8e8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  macroLabel: {
    fontSize: 12,
    color: Palette.gray,
    marginBottom: 6,
    fontWeight: '500',
  },
  macroValue: {
    fontSize: 20,
    fontWeight: '700',
    color: Palette.primary,
  },
  // Option buttons - Enhanced with celebration effect
  optionButton: {
    backgroundColor: Palette.primary,
    padding: 19,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: Palette.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 14,
    elevation: 7,
  },
  optionButtonText: {
    color: Palette.white,
    fontSize: 19,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  // Quantity container
  quantityContainer: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: Palette.lightGray2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  quantityLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: Palette.darkGray,
  },
  quantityInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  quantityButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    color: Palette.white,
    fontSize: 24,
    fontWeight: 'bold',
  },
  quantityInput: {
    width: '50%',
    minWidth: 80,
    maxWidth: 220,
    backgroundColor: Palette.white,
    padding: 12,
    borderRadius: 8,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
    borderWidth: 2,
    borderColor: Palette.primary,
  },
  // Serving size - Enhanced card styling
  servingSizeContainer: {
    marginBottom: 20,
    padding: 16,
    backgroundColor: Palette.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  servingSizeLabel: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 12,
    color: Palette.darkGray,
  },
  servingSizeInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 12,
    marginBottom: 12,
    justifyContent: 'space-between',
  },
  servingSizeInput: {
    width: '50%',
    minWidth: 80,
    maxWidth: 220,
    backgroundColor: '#f8f8f8',
    padding: 10,
    borderRadius: 10,
    fontSize: 17,
    textAlign: 'center',
    fontWeight: '600',
    borderWidth: 2,
    borderColor: Palette.primary,
  },
  servingSizeUnit: {
    fontSize: 15,
    fontWeight: '600',
    color: Palette.darkGray,
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 70,
    textAlign: 'center',
  },
  servingSizeHint: {
    fontSize: 12,
    color: Palette.gray,
    marginTop: 8,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  servingSizeLabelRow: {
    marginBottom: 14,
  },
  // Unified amount container - combines serving size & total amount
  unifiedAmountContainer: {
    marginBottom: 20,
    padding: 18,
    backgroundColor: Palette.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  amountSection: {
    marginBottom: 0,
    paddingBottom: 12,
  },
  dividerLine: {
    height: 1,
    backgroundColor: '#e8e8e8',
    marginVertical: 20,
  },
  // Meal container - Enhanced styling
  mealContainer: {
    marginBottom: 20,
    padding: 18,
    backgroundColor: Palette.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  mealChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 14,
  },
  mealChip: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: '#f0f0f0',
    borderWidth: 1.5,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  mealChipActive: {
    backgroundColor: Palette.primary,
    borderColor: Palette.primary,
    shadowColor: Palette.primary,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  mealChipText: {
    color: Palette.darkGray,
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0.2,
  },
  mealChipTextActive: {
    color: Palette.white,
  },
  // Custom amount
  customAmountContainer: {
    marginBottom: 12,
    padding: 16,
    backgroundColor: Palette.lightGray,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Palette.orange,
  },
  customLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: Palette.brown,
  },
  customInputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  customInput: {
    flex: 1,
    backgroundColor: Palette.white,
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: Palette.primary,
  },
  customButton: {
    backgroundColor: Palette.primary,
    paddingHorizontal: 24,
    borderRadius: 8,
    justifyContent: 'center',
  },
  customButtonText: {
    color: Palette.white,
    fontSize: 16,
    fontWeight: '600',
  },
  achievementBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#fff3cd',
    marginTop: 6,
    alignSelf: 'flex-start',
  },
  achievementBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#856404',
  },
  cancelOptionButton: {
    padding: 16,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e0e0e0',
    backgroundColor: '#f5f5f5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  cancelOptionText: {
    color: Palette.darkGray,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  // Unit selector - Enhanced with better visual feedback
  unitSelector: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 0,
    marginBottom: 18,
    alignItems: 'center',
  },
  unitButton: {
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
    borderWidth: 1.5,
    borderColor: '#ddd',
  },
  unitButtonActive: {
    backgroundColor: Palette.primary,
    borderColor: Palette.primary,
  },
  unitButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: Palette.darkGray,
  },
  unitButtonTextActive: {
    color: Palette.white,
  },
});
